import React from "react";
import Navigation from "@/components/navigation/navigation";
import styles from "./whoweare.module.css";
import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";
import 'bootstrap/dist/css/bootstrap.min.css';

const WhoWeAre = () => {
  return (
    <>
      <Header />
    <div>
      <Navigation /> {/* Use Navigation component instead of Navbar */}
      <main>
        <div className="container">
          <div className="row">
            <div className="col-6">
              <img src="/images/about-pic4.jpg" className={`${styles.image4} img-fluid`} />
            </div>
            </div>
          <div className="row">
            <div className="col-12">
              <div className={styles.content1}>
              <div className={styles.container1}>
              <div className={styles.content}>
                <h1>Who We <span style={{ color: '#009673' }}>Are</span></h1>
                <p>
                  Our team is dedicated to helping our clients tap into the vast
                  potential of IoT technology, enabling them to collect and analyze
                  data from connected devices and make more informed data-driven
                  decisions. We offer a range of services, including IoT consulting,
                  system design and deployment, and ongoing support and maintenance.
                </p>
                <p>
                  Our passion for technology and our deep understanding of the
                  African market allows us to deliver solutions that are tailored to
                  the unique needs of our clients. Whether you are a small business
                  looking to streamline your operations or a large corporation
                  seeking to transform your industry, we have the expertise and
                  experience to help you succeed.
                </p>
              </div>
            </div>
          </div>
          </div>
          </div>
          
          <div className="row">
            <div className="col-6">
              <img src="/images/about-pic.jpg" className={`${styles.image5} img-fluid`} />
            </div>
          </div>
          <div className="row">
            <div className="col-12">
              <div className={styles.content4}>
                <div className={styles.container2}>
                  <div className={styles.content}>
                    <h1>Why Choose Us?</h1>
                    <p>
                      1- Innovative technology and solutions: We help customers
                      connect and manage their devices, as well as solutions that help
                      them analyse and make use of the data generated by those
                      devices.
                    </p>
                    <p>
                      2- Quality and reliability: We commit to provide excellent
                      customer service and support to help customers get the most out
                      of their IoT solutions.
                    </p>
                    <p>
                      3- Transparency : We are open about how our products and
                      services work. We empower our customers by providing them with
                      the tools and support they need to succeed in their own IoT
                      projects.
                    </p>
                    <p>
                      4 – IOT Awareness : We are building awareness and understanding
                      of IoT technology among potential customers in Africa.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
    </>
  );
};

export default WhoWeAre;
